version: '3'
services:
  jupyter:
    build: ./docker
    ports:
      - "8888:8888"
    volumes:
      - ./:/notebooks
    command: ["/bin/bash", "-c", "cd /notebooks && jupyter notebook --ip=0.0.0.0 --allow-root"]